### ISSUE TITLE
TODO Entrega Funciones

### ISSUE THREAD

**Issue by LiteMasteralex** [LiteMasteralex/-Jitters#4]
- [x] 1. Generacion de quadruplos para funciones retornos
- [x] 2. Asignacion y creacion de variables para funciones retornos (Lo que explico elda que seria buena idea guardar el resultado en una variable (no se si el resultado se guarda a que onda))
- [x] 3. Verificacion de Retornos
- [x] 4. Count de temorales de las funciones_retorno 
- [x] 5. Check que funciones no existan en variables y viceversa
